# -*- coding: utf-8 -*-
"""
step006_simulacion_paths.py
Simulación de paths acumulados sobre predicciones cuantílicas de step005.

═══════════════════════════════════════════════════════════════════════════════
FLUJO
═══════════════════════════════════════════════════════════════════════════════
  1. Lee predicciones cuantílicas por fold guardadas por step005
     (parquets: preds_test_fold<k>_<banco>.parquet, columnas:
      fecha_t | h | y_realizado | q01 | q05 | q50 | q95 | q99)

  2. Por cada (fecha_t, h) fitea una distribución split-t (skew-t de dos
     piezas) a los 5 cuantiles predichos.  Parámetros: loc, scale_l,
     scale_r, df.  La inversa (PPF) se evalúa vía scipy.stats.t.ppf.

  3. Por cada fecha de origen t en el período de evaluación:
       a. Sortea una secuencia de régimen de 1..H_MAX días usando la
          matriz de transición del HMM (cadena de Markov discreta).
       b. Genera H_MAX variables normales independientes w_k.
       c. Aplica la recursión AR(1) para obtener z_k correlacionados:
            z_1 = w_1
            z_k = ρ_s(k) · z_{k-1}  +  √(1 − ρ_s(k)²) · w_k
          donde ρ_s(k) es la correlación del régimen vigente en el paso k.
          Esto es matemáticamente equivalente a la cópula gaussiana con
          decaimiento geométrico ρ^|h1-h2|, implementada como el
          algoritmo de Thomas sobre Cholesky de Σ tridiagonal.
       d. Transforma z_k a uniforme: u_k = Φ(z_k).
       e. Invierte con la PPF de la split-t calibrada para el horizonte k:
            r_k = F_inv_h=k(u_k)
       f. Si se provee Prophet: flujo_k = prophet_k + r_k.
          Si no: flujo_k = r_k  (predicción cuantílica directa).

  4. Acumula cada path por ventanas de plazo (ventanas = [1,5,22,75]).
     El percentil de estrés del acumulado se lee directamente de la
     distribución de sumas — sin sumar percentiles diarios.

  5. Calcula tres piezas de backtest:
       Pieza 1 — tasa de violación con corrección Newey-West por solapamiento.
       Pieza 2 — test de duraciones de Christoffersen-Pelletier.
       Pieza 3 — PIT (Probability Integral Transform) con test Anderson-Darling.

═══════════════════════════════════════════════════════════════════════════════
INTEGRACIÓN CON STEP005 — solo 3 líneas nuevas
═══════════════════════════════════════════════════════════════════════════════
  En step005, en la sección de configuración (junto a GUARDAR_MODELO_FINAL):

      # True → guarda predicciones TEST por fold para step006
      GUARDAR_PREDS_TEST = True

  En el loop de folds, justo DESPUÉS de las dos líneas de calibración
  post-hoc (preds_test = {tau: arr + _adj_test ...} / preds_val = ...):

      if GUARDAR_PREDS_TEST and not SOLO_REGENERAR_PLOTS:
          _guardar_preds_test(
              preds_test, y_test.values, h_test, fechas_t_test,
              fold["fold"], banco, fecha_hoy, DIR_MODO)

  Y define la función _guardar_preds_test en step005 (PARTE 7 o 8):

      def _guardar_preds_test(preds, y_real, h_arr, fechas_t, fold_num,
                              banco, fecha_hoy, dir_out):
          rows = {f"q{int(tau*100):02d}": arr
                  for tau, arr in preds.items() if tau != "mean"}
          df = pd.DataFrame({
              "fecha_t": pd.DatetimeIndex(fechas_t),
              "h"      : h_arr.astype(int),
              "y_realizado": y_real,
              **rows,
          })
          ruta = dir_out / f"preds_test_fold{fold_num:02d}_{banco}_{fecha_hoy}.parquet"
          df.to_parquet(ruta, index=False)
"""

from __future__ import annotations

import logging
import multiprocessing
import os
import warnings
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd
from scipy import stats, optimize
import matplotlib
matplotlib.use("Agg")   # backend no interactivo — necesario para generar PNGs
                        # sin pantalla (correr desde script/consola, no notebook)
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore", category=RuntimeWarning)
logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 1 — Azzalini-Capitanio skew-t (AC2003)
# ══════════════════════════════════════════════════════════════════════════════
#
# Referencia: Azzalini, A. & Capitanio, A. (2003). "Distributions generated by
# perturbation of symmetry with emphasis on a multivariate skew-t distribution."
# Journal of the Royal Statistical Society B, 65(2), 367-389.
#
# Parámetros: xi (localización), omega (escala > 0), alpha (forma ∈ ℝ), nu (df > 2)
#
# PDF:  f(x; xi, omega, alpha, nu) =
#         (2/omega) · t_nu((x-xi)/omega) · T_{nu+1}(alpha · z · sqrt((nu+1)/(nu+z²)))
#
# donde z = (x-xi)/omega, t_nu = PDF de t-Student con nu df,
#       T_{nu+1} = CDF de t-Student con nu+1 df  ← clave AC2003 (no nu).
#
# CDF: No tiene forma cerrada. Se calcula vía cuadratura Gauss-Legendre con
#      cambio de variable u = t/(1+|t|) que compacta ℝ en (-1,1), permitiendo
#      nodos fijos y pesos fijos precomputados para integración vectorizada.
#
# PPF: Sin forma cerrada. Se precalcula una malla de 200 cuantiles con Newton
#      (usando el PDF analítico como derivada), y luego se interpola linealmente.
#      La malla se construye una sola vez por objeto (lazy o eagerly en fitear_skewt).

# Nodos y pesos GL de grado 80 precomputados a nivel de módulo (thread-safe,
# inmutables). Orden 80 garantiza ~15 dígitos de precisión para funciones suaves.
_GL_NODES, _GL_WEIGHTS = np.polynomial.legendre.leggauss(80)


class AzzaliniT:
    """
    Distribución skew-t de Azzalini & Capitanio (2003).

    Parámetros
    ----------
    xi    : localización
    omega : escala (> 0)
    alpha : forma/asimetría (ℝ; alpha=0 → t-Student simétrica)
    nu    : grados de libertad (> 2 para varianza finita)
    """

    _PPF_N     = 200          # puntos en la malla de PPF
    _PPF_U_MIN = 1e-4         # límite inferior de la malla (evita divergencia)
    _PPF_U_MAX = 1.0 - 1e-4  # límite superior
    _PPF_ITER  = 20           # máximo de iteraciones Newton
    _PPF_TOL   = 1e-9         # tolerancia de convergencia Newton

    __slots__ = ("xi", "omega", "alpha", "nu", "_ppf_u", "_ppf_x")

    def __init__(self, xi: float, omega: float, alpha: float, nu: float):
        self.xi    = float(xi)
        self.omega = max(float(omega), 1e-12)
        self.alpha = float(alpha)
        self.nu    = max(float(nu), 2.01)
        self._ppf_u: np.ndarray | None = None
        self._ppf_x: np.ndarray | None = None

    # ── PDF analítico ─────────────────────────────────────────────────────────

    def _pdf_std(self, z: np.ndarray) -> np.ndarray:
        """
        PDF estandarizada (xi=0, omega=1) en un array de puntos z.
        Implementa exactamente la ecuación (4) de AC2003:
          2 · t_nu(z) · T_{nu+1}(alpha · z · sqrt((nu+1)/(nu+z²)))
        Nota: T_{nu+1} usa nu+1 grados de libertad — detalle crítico de AC2003.
        """
        t_pdf = stats.t.pdf(z, df=self.nu)
        with np.errstate(invalid="ignore", divide="ignore"):
            denom = np.maximum(self.nu + z ** 2, 1e-300)
            inner = self.alpha * z * np.sqrt((self.nu + 1.0) / denom)
        t_cdf = stats.t.cdf(inner, df=self.nu + 1.0)   # nu+1, no nu
        return 2.0 * t_pdf * t_cdf

    def pdf(self, x) -> np.ndarray:
        x = np.atleast_1d(np.asarray(x, dtype=float))
        return self._pdf_std((x - self.xi) / self.omega) / self.omega

    # ── CDF vía Gauss-Legendre vectorizado ────────────────────────────────────

    def _cdf_batch(self, z_arr: np.ndarray) -> np.ndarray:
        """
        CDF estandarizada en un array de puntos z_arr, calculada simultáneamente.

        Cambio de variable: u = t/(1+|t|) compacta ℝ → (-1,1).
          Inversa: t = u/(1-|u|)
          Jacobiano: dt/du = 1/(1-|u|)²
        Integración GL en [-1, u_upper] donde u_upper = z/(1+|z|).

        Vectoriza sobre z_arr: construye tensor (n_z × n_GL) en un solo bloque
        numpy, evitando el loop Python sobre puntos z. Esencial para que el
        cálculo de la malla PPF sea viable con decenas de miles de objetos.
        """
        n_z  = len(z_arr)
        n_gl = len(_GL_NODES)

        u_up = np.clip(z_arr / (1.0 + np.abs(z_arr)), -1.0 + 1e-9, 1.0 - 1e-9)

        hw  = (u_up + 1.0) * 0.5        # (n_z,)
        mid = (u_up - 1.0) * 0.5        # (n_z,)

        # Nodos GL mapeados a [a_i, b_i] para cada z_i — tensor (n_z, n_gl)
        u_pts   = hw[:, None] * _GL_NODES[None, :] + mid[:, None]
        abs_u   = np.minimum(np.abs(u_pts), 1.0 - 1e-12)
        t_pts   = u_pts / (1.0 - abs_u)
        jac     = 1.0 / (1.0 - abs_u) ** 2

        # Integrando = 2 · t_nu(t) · T_{nu+1}(alpha·t·sqrt((nu+1)/(nu+t²))) · jac
        flat    = t_pts.ravel()
        t_pdf_v = stats.t.pdf(flat, df=self.nu).reshape(n_z, n_gl)
        with np.errstate(invalid="ignore", divide="ignore"):
            inner_v = (self.alpha * t_pts *
                       np.sqrt((self.nu + 1.0) /
                                np.maximum(self.nu + t_pts ** 2, 1e-300)))
        t_cdf_v = stats.t.cdf(inner_v.ravel(), df=self.nu + 1.0).reshape(n_z, n_gl)

        integrand = 2.0 * t_pdf_v * t_cdf_v * jac      # (n_z, n_gl)
        result    = hw * np.einsum("j,ij->i", _GL_WEIGHTS, integrand)
        return np.clip(result, 0.0, 1.0)

    def cdf(self, x) -> np.ndarray:
        x = np.atleast_1d(np.asarray(x, dtype=float))
        return self._cdf_batch((x - self.xi) / self.omega)

    # ── PPF vía malla precomputada ────────────────────────────────────────────

    def _build_ppf_grid(self) -> None:
        """
        Construye la malla PPF usando brentq — más robusto que Newton para
        alpha extremos donde Newton diverge al cruzar regiones de PDF≈0.

        Bracket: rango de la t-Student simétrica (misma nu) ampliado por la
        asimetría de la AC — para alpha>0 la masa va a la derecha (hi más ancho);
        para alpha<0 a la izquierda (lo más ancho). Factor 12*|alpha| garantiza
        cubrir la distribución incluso para alpha=±15.
        """
        from scipy.optimize import brentq as _brentq

        u_grid = np.linspace(self._PPF_U_MIN, self._PPF_U_MAX, self._PPF_N)

        # Bracket ancho ajustado por dirección de asimetría
        t_lo = float(stats.t.ppf(1e-8, df=self.nu))
        t_hi = float(stats.t.ppf(1.0 - 1e-8, df=self.nu))
        skew_shift = float(np.clip(self.alpha, -15.0, 15.0))
        lo = (t_lo + min(skew_shift, 0) * 12.0) * self.omega + self.xi
        hi = (t_hi + max(skew_shift, 0) * 12.0) * self.omega + self.xi

        x_grid = np.empty(self._PPF_N)
        for i, u_i in enumerate(u_grid):
            try:
                x_grid[i] = _brentq(
                    lambda x: float(self._cdf_batch(
                        np.array([(x - self.xi) / self.omega]))[0]) - u_i,
                    lo, hi,
                    xtol=self._PPF_TOL, maxiter=self._PPF_ITER * 3,
                )
            except Exception as _e_brentq:
                logger.debug(
                    f"AzzaliniT._build_ppf_grid: brentq falló en u={u_i:.4f} "
                    f"(xi={self.xi:.3g}, omega={self.omega:.3g}, "
                    f"alpha={self.alpha:.3g}, nu={self.nu:.1f}) → "
                    f"{type(_e_brentq).__name__}: {_e_brentq} — usando fallback t-simétrica"
                )
                x_grid[i] = float(stats.t.ppf(u_i, df=self.nu)) * self.omega + self.xi

        # Garantizar monotonicidad estricta (brentq puede producir empates en extremos)
        for i in range(1, len(x_grid)):
            if x_grid[i] <= x_grid[i - 1]:
                x_grid[i] = x_grid[i - 1] + 1e-10

        self._ppf_u = u_grid
        self._ppf_x = x_grid

    def ppf(self, u) -> np.ndarray:
        """
        Función cuantil vía interpolación lineal sobre la malla precomputada.
        Construye la malla en la primera llamada si no existe (lazy init).
        En fitear_skewt se construye eagerly para que sea thread-safe durante
        el multiprocessing del pipeline.
        """
        if self._ppf_u is None:
            self._build_ppf_grid()
        u = np.atleast_1d(np.asarray(u, dtype=float))
        return np.interp(np.clip(u, self._ppf_u[0], self._ppf_u[-1]),
                         self._ppf_u, self._ppf_x)


# Alias de compatibilidad — el resto del código que usa SplitT como nombre
# de tipo sigue funcionando sin cambios en los type hints.
SplitT = AzzaliniT


def fitear_skewt(
    q_vals,
    taus:     list[float],
    n_starts: int = 3,
) -> AzzaliniT:
    """
    Ajusta una AzzaliniT (AC2003) a los cuantiles predichos por XGBoost.

    Diferencia clave respecto a la SplitT anterior:
    - Parámetros: xi (loc), omega (escala única), alpha (forma), nu (df).
    - Objetivo: minimizar Σ (CDF(q_τi; ·) − τi)²  en espacio NORMALIZADO.
      Usar la CDF como objetivo (no la PPF) es más eficiente porque evalúa
      la CDF en los q_τi conocidos — O(5 × n_GL) por evaluación del objetivo —
      sin necesitar búsqueda de raíces.
    - Se normaliza antes de optimizar (mediana=0, spread=1) y se desnormaliza
      al final, igual que antes, para invariancia de escala.
    - Tras encontrar los mejores parámetros, construye la malla PPF eagerly
      para que el multiprocessing de fitear_distribuciones_por_horizonte la
      compute en paralelo (no en la simulación, que puede ser serial).

    Devuelve
    --------
    AzzaliniT calibrada en la escala original de q_vals, con malla PPF lista.
    """
    if isinstance(q_vals, dict):
        q_arr = np.array([q_vals[t] for t in taus], dtype=float)
    else:
        q_arr = np.asarray(q_vals, dtype=float)
    taus_arr = np.array(taus, dtype=float)

    # ── Normalización ─────────────────────────────────────────────────────────
    med_idx   = min(range(len(taus)), key=lambda i: abs(taus[i] - 0.50))
    loc0_orig = q_arr[med_idx]
    escala    = max(q_arr.max() - q_arr.min(), 1e-9)
    q_norm    = (q_arr - loc0_orig) / escala

    # Asimetría empírica de los cuantiles: guía el alpha inicial
    spread = max(q_norm.max() - q_norm.min(), 1e-6)
    asym   = (q_norm[-1] - q_norm[med_idx]) - (q_norm[med_idx] - q_norm[0])
    alpha0 = float(np.clip(asym / (spread * 0.5 + 1e-9) * 3, -8, 8))

    # Puntos de inicio: simétrico + con asimetría detectada + asimetría opuesta
    starts = [
        [0.0, spread * 0.40,  0.0,    6.0],
        [0.0, spread * 0.35,  alpha0, 4.0],
        [0.0, spread * 0.35, -alpha0, 4.0],
    ][:n_starts]

    bounds = [
        (q_norm.min() - spread, q_norm.max() + spread),  # xi_n
        (1e-6,  8.0 * spread),                            # omega_n
        (-15.0, 15.0),                                     # alpha
        (2.01,  120.0),                                    # nu
    ]

    def objetivo(params: np.ndarray) -> float:
        xi_n, omega_n, alpha_n, nu_n = params
        if omega_n <= 0 or nu_n <= 2.0:
            return 1e6
        try:
            dist_n = AzzaliniT(xi_n, omega_n, alpha_n, nu_n)
            z_vals  = (q_norm - xi_n) / omega_n
            cdf_hat = dist_n._cdf_batch(z_vals)
            return float(np.sum((cdf_hat - taus_arr) ** 2))
        except Exception as _e_obj:
            logger.debug(f"fitear_skewt objetivo: excepción con params={params} → "
                         f"{type(_e_obj).__name__}: {_e_obj}")
            return 1e6

    mejor = None
    for x0 in starts:
        try:
            res = optimize.minimize(
                objetivo, x0, method="L-BFGS-B", bounds=bounds,
                options={"maxiter": 800, "ftol": 1e-15, "gtol": 1e-11},
            )
            if mejor is None or res.fun < mejor.fun:
                mejor = res
        except Exception as _e_opt:
            logger.debug(f"fitear_skewt: optimize.minimize falló con x0={x0} → "
                         f"{type(_e_opt).__name__}: {_e_opt}")

    # Umbral: SSE < 0.005 ~ error medio de 3 pp por cuantil — ajuste aceptable.
    if mejor is not None and mejor.fun < 0.005:
        xi_n, omega_n, alpha_n, nu_n = mejor.x
        xi    = xi_n * escala + loc0_orig
        omega = omega_n * escala
        dist  = AzzaliniT(xi, omega, alpha_n, nu_n)
        dist._build_ppf_grid()   # eager: se paraleliza con fitear_distribuciones
        return dist

    # Fallback: t-Student simétrica (alpha=0)
    logger.warning("fitear_skewt: fallo AC2003, usando fallback t-Student simétrico")
    iqr = max((q_arr[-1] - q_arr[0]) / 4.0, 1.0)
    dist = AzzaliniT(loc0_orig, iqr, 0.0, 6.0)
    dist._build_ppf_grid()
    return dist

# ══════════════════════════════════════════════════════════════════════════════
# PARTE 2 — Fitting masivo por horizonte
# ══════════════════════════════════════════════════════════════════════════════

# ══════════════════════════════════════════════════════════════════════════════
# PARTE 2 — Fitting masivo por horizonte
# ══════════════════════════════════════════════════════════════════════════════

TAUS_STD = [0.01, 0.05, 0.50, 0.95, 0.99]


def _worker_fitear_uno(args: tuple) -> tuple:
    """
    Worker de multiprocessing para fitear_distribuciones_por_horizonte.
    Debe ser función de MÓDULO (no closure/lambda local) para que
    multiprocessing pueda picklearla y enviarla a los procesos hijos en
    Windows (spawn) — una función anidada o un lambda no son picklables ahí.
    """
    key, q_vals, taus = args
    q_arr = np.asarray(q_vals, dtype=float)
    if np.any(np.isnan(q_arr)):
        idx_med = len(taus) // 2
        loc = float(q_arr[idx_med]) if not np.isnan(q_arr[idx_med]) else 0.0
        return key, AzzaliniT(loc, 1.0, 0.0, 6.0)   # alpha=0 → t-Student simétrica
    return key, fitear_skewt(q_vals, taus)


def fitear_distribuciones_por_horizonte(
    df_preds: pd.DataFrame,
    taus: list[float] | None = None,
    n_jobs: int = -1,
) -> dict[tuple, SplitT]:
    """
    Para cada combinación única (fecha_t, h) en df_preds, fitea una SplitT
    a los cuantiles predichos (skew-t completa: asimetría + colas con grados
    de libertad finitos — deliberadamente más flexible y más costosa que una
    aproximación cerrada).

    Cada fit es una optimización no lineal (~0.2s) — sobre miles de filas
    (orígenes × horizontes) el cómputo serial es impracticable, por eso se
    paraleliza con multiprocessing.

    Columnas requeridas: fecha_t, h, q01, q05, q50, q95, q99
    (o las que correspondan a los taus indicados).

    Parámetros
    ----------
    n_jobs : -1 usa todos los cores disponibles (os.cpu_count()); 1 fuerza
             ejecución serial (depuración, o entornos sin soporte de
             multiprocessing). Con <50 filas siempre corre serial (el
             overhead de levantar procesos no se justifica).

    Devuelve
    --------
    dict  {(fecha_t, h): SplitT}
    """
    if taus is None:
        taus = TAUS_STD

    col_map = {tau: f"q{int(tau*100):02d}" for tau in taus}
    missing = [c for c in col_map.values() if c not in df_preds.columns]
    if missing:
        raise ValueError(f"Columnas faltantes en df_preds: {missing}")

    # Normalizar fecha_t a pd.Timestamp y h a Python int en la clave,
    # para que el hash del dict sea siempre consistente con el lookup en
    # simular_un_path — np.int64 y int tienen el mismo valor pero pueden
    # diferir en comportamiento de hash en versiones antiguas de CPython,
    # y Timestamp vs str claramente difieren.
    tareas = []
    for row in df_preds.itertuples(index=False):
        key = (pd.Timestamp(row.fecha_t), int(row.h))
        q_vals = [getattr(row, col_map[t]) for t in taus]
        tareas.append((key, q_vals, list(taus)))

    total = len(tareas)
    n_procesos = os.cpu_count() if n_jobs == -1 else n_jobs
    logger.info(f"    [step006] Fiteando {total} distribuciones split-t "
               f"(n_jobs={n_procesos if (n_jobs != 1 and total >= 50) else 1})...")

    if n_jobs == 1 or total < 50:
        resultados = [_worker_fitear_uno(t) for t in tareas]
    else:
        try:
            with multiprocessing.Pool(processes=n_procesos) as pool:
                chunksize = max(1, total // (n_procesos * 4))
                resultados = pool.map(_worker_fitear_uno, tareas, chunksize=chunksize)
        except Exception as e:
            logger.warning(f"    [step006] multiprocessing falló ({e}); "
                          f"usando ejecución serial.")
            resultados = [_worker_fitear_uno(t) for t in tareas]

    distribuciones = dict(resultados)
    logger.info(f"    [step006] {len(distribuciones)} distribuciones fiteadas")
    return distribuciones


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 3 — Simulación de régimen (cadena de Markov del HMM)
# ══════════════════════════════════════════════════════════════════════════════

def simular_regimen_path(
    estado_inicial: int,
    matriz_transicion: np.ndarray,
    n_pasos: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Simula una secuencia de estados de régimen para n_pasos horizontes.
    matriz_transicion[i, j] = P(S_{t+1}=j | S_t=i).
    Devuelve array de shape (n_pasos,) con int de 0 a n_estados-1.
    """
    n_estados = matriz_transicion.shape[0]
    estados   = np.empty(n_pasos, dtype=int)
    estados[0] = estado_inicial
    umbrales   = np.cumsum(matriz_transicion, axis=1)  # pre-computa CDF por fila

    for k in range(1, n_pasos):
        v = rng.random()
        row = umbrales[estados[k - 1]]
        estados[k] = int(np.searchsorted(row, v, side="right"))
        estados[k] = min(estados[k], n_estados - 1)  # seguridad

    return estados


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 4 — Simulación de un path via recursión AR(1) + PPF de split-t
# ══════════════════════════════════════════════════════════════════════════════
#
# Equivalencia con cópula gaussiana (ver HTML del marco metodológico):
#
#   La recursión  z_k = ρ_s(k) · z_{k-1} + √(1-ρ_s(k)²) · w_k
#   ES la factorización de Cholesky de una Σ AR(1) con ρ variable en el tiempo,
#   implementada como el algoritmo de Thomas (O(n)) en lugar de Cholesky general
#   (O(n³)). La dependencia está en la salida z; los insumos w_k son independientes.

def simular_un_path(
    fecha_t:          pd.Timestamp | str,
    horizontes:       np.ndarray,
    regimenes_path:   np.ndarray,
    rho_por_regimen:  dict[int, float],
    distribuciones:   dict[tuple, SplitT],
    rng:              np.random.Generator,
) -> np.ndarray:
    """
    Genera un path de residuos/flujos para los horizontes pedidos desde fecha_t.

    Parámetros
    ----------
    fecha_t         : fecha de origen.
    horizontes      : array [1, 2, ..., H_MAX] (índices del path).
    regimenes_path  : array de estados de régimen por cada horizonte.
    rho_por_regimen : {estado: ρ_s}, correlación AR(1) por régimen.
    distribuciones  : dict {(fecha_t, h): SplitT} — marginales calibradas.
    rng             : generador de números aleatorios.

    Devuelve
    --------
    array de shape (len(horizontes),) con residuos simulados en escala real.
    """
    n   = len(horizontes)
    w   = rng.standard_normal(n)          # ruido independiente (insumo de Thomas)
    z   = np.empty(n)
    z[0] = w[0]

    for k in range(1, n):
        rho   = rho_por_regimen.get(regimenes_path[k], 0.0)
        z[k]  = rho * z[k - 1] + np.sqrt(max(1.0 - rho**2, 0.0)) * w[k]

    u = stats.norm.cdf(z)                 # uniforme correlacionada [0,1]

    residuos = np.empty(n)
    for k, h in enumerate(horizontes):
        key  = (pd.Timestamp(fecha_t), int(h))
        dist = distribuciones.get(key)
        if dist is None:
            residuos[k] = 0.0
        else:
            residuos[k] = float(dist.ppf(np.clip(u[k], 1e-7, 1.0 - 1e-7))[0])

    return residuos


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 5 — Simulación masiva de paths y acumulado por ventana
# ══════════════════════════════════════════════════════════════════════════════

def _resolver_estado_inicial(estado_inicial, fecha_t, default: int = 0) -> int:
    """
    Permite que estado_inicial sea:
      - un int  : mismo estado para todos los orígenes (comportamiento original,
                  útil para proyectar hacia adelante desde "hoy").
      - un dict o pd.Series {fecha_t: estado} : estado propio de CADA origen,
                  el caso correcto para backtest histórico — usa el régimen
                  que el HMM clasificó ese día específico (columna 'regimen_hmm'
                  ya guardada por step005_walk_forward_cv*.py), en vez de asumir
                  que todo el período de test parte del mismo régimen.
    Si fecha_t no está en el mapeo, devuelve `default` (con aviso una sola vez
    por ejecución, vía logger, no por cada origen — evita espamear el log).
    """
    if isinstance(estado_inicial, (dict, pd.Series)):
        try:
            val = estado_inicial[fecha_t]
        except KeyError:
            return default
        if pd.isna(val):
            return default
        return int(val)
    return int(estado_inicial)


def simular_paths_por_origen(
    fecha_t:          pd.Timestamp,
    df_origen:        pd.DataFrame,
    distribuciones:   dict[tuple, SplitT],
    estado_inicial:   int,
    matriz_transicion: np.ndarray,
    rho_por_regimen:  dict[int, float],
    n_paths:          int,
    ventanas:         list[int],
    prophet_col:      str | None = "prophet_pred",
    seed:             int = 42,
) -> dict[int, np.ndarray]:
    """
    Para una fecha de origen dada, simula n_paths paths y devuelve la
    distribución del flujo acumulado para cada ventana.

    Parámetros
    ----------
    fecha_t           : fecha de origen del forecast.
    df_origen         : filas de df_preds con fecha_t == fecha_t,
                        ordenadas por h ascendente.
    distribuciones    : dict {(fecha_t, h): SplitT}.
    estado_inicial    : estado HMM actual (int).
    matriz_transicion : array (n_estados × n_estados).
    rho_por_regimen   : {estado: ρ_s}.
    n_paths           : número de paths a simular.
    ventanas          : lista de plazos en días hábiles, e.g. [1,5,22,75].
    prophet_col       : nombre de la columna con el forecast determinista de
                        Prophet (None si no se usa).
    seed              : semilla base para reproducibilidad.

    Devuelve
    --------
    dict {ventana: array de shape (n_paths,)} — distribuciones del acumulado.
    """
    df_origen = df_origen.sort_values("h").reset_index(drop=True)
    horizontes = df_origen["h"].values.astype(int)
    H          = len(horizontes)

    prophet_vals = (
        df_origen[prophet_col].values
        if (prophet_col is not None and prophet_col in df_origen.columns)
        else np.zeros(H)
    )

    rng_base  = np.random.default_rng(seed)
    # Simular secuencias de régimen (una por path)
    # Reutilizamos la misma semilla base pero streams independientes por path
    acum_por_ventana: dict[int, list[float]] = {v: [] for v in ventanas}

    for p in range(n_paths):
        rng_p = np.random.default_rng(seed + p)

        # Sorteo 1: secuencia de régimen
        regimenes = simular_regimen_path(
            estado_inicial, matriz_transicion, H, rng_p)

        # Sorteo 2: residuos correlacionados vía AR(1) copula
        residuos = simular_un_path(
            fecha_t, horizontes, regimenes,
            rho_por_regimen, distribuciones, rng_p)

        # Flujo simulado = Prophet + residuo
        flujos = prophet_vals + residuos

        # Acumular por cada ventana
        for v in ventanas:
            idx = np.where(horizontes <= v)[0]
            if len(idx) > 0:
                acum_por_ventana[v].append(float(flujos[idx].sum()))
            else:
                acum_por_ventana[v].append(0.0)

    return {v: np.array(lst) for v, lst in acum_por_ventana.items()}


def calcular_percentiles_acumulado(
    distribuciones_acum: dict[int, np.ndarray],
    taus_output:         list[float] | None = None,
) -> dict[int, dict[float, float]]:
    """
    Extrae percentiles de la distribución del acumulado por ventana.

    Devuelve
    --------
    dict {ventana: {tau: valor_percentil}}
    """
    if taus_output is None:
        taus_output = [0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]

    resultado = {}
    for v, arr in distribuciones_acum.items():
        resultado[v] = {t: float(np.quantile(arr, t)) for t in taus_output}
    return resultado


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 6 — Pipeline completo: múltiples orígenes
# ══════════════════════════════════════════════════════════════════════════════

def pipeline_simulacion(
    df_preds:          pd.DataFrame,
    estado_inicial:    int | dict | pd.Series,
    matriz_transicion: np.ndarray,
    rho_por_regimen:   dict[int, float],
    ventanas:          list[int]  | None = None,
    taus_input:        list[float] | None = None,
    taus_output:       list[float] | None = None,
    n_paths:           int  = 1000,
    prophet_col:       str | None = "prophet_pred",
    h_col:             str  = "h",
    fecha_col:         str  = "fecha_t",
    seed:              int  = 42,
    n_jobs:            int  = -1,
    distribuciones:    dict[tuple, SplitT] | None = None,
) -> pd.DataFrame:
    """
    Pipeline completo para todas las fechas de origen en df_preds.

    Parámetros
    ----------
    df_preds          : DataFrame con predicciones de step005, columnas:
                         fecha_t | h | y_realizado | q01 | q05 | q50 | q95 | q99
                         (+ prophet_pred opcional).
    estado_inicial    : estado HMM a usar como punto de partida de cada origen.
                         - int: mismo estado para TODOS los orígenes (proyección
                           hacia adelante desde "hoy", como en el test sintético).
                         - dict o pd.Series {fecha_t: estado}: el estado propio
                           de CADA origen (correcto para backtest histórico —
                           usa la columna 'regimen_hmm' real de cada fila).
    matriz_transicion : array (n_estados × n_estados) del HMM.
    rho_por_regimen   : {estado: ρ_s}, un ρ por régimen.
    ventanas          : plazos en días hábiles, default [1, 5, 22, 75].
    taus_input        : cuantiles del df_preds, default [0.01,0.05,0.50,0.95,0.99].
    taus_output       : cuantiles del acumulado a reportar.
    n_paths           : paths por fecha de origen.
    prophet_col       : columna con forecast de Prophet (None si no aplica).
    seed              : semilla base.
    n_jobs            : procesos paralelos para fitear las distribuciones
                         (ver fitear_distribuciones_por_horizonte). -1 = todos
                         los cores; 1 = serial.
    distribuciones    : dict {(fecha_t,h): SplitT} ya fiteado, si se quiere
                         REUSAR el ajuste (p.ej. compartido con
                         generar_fancharts_todos_origenes para no fitear las
                         mismas skew-t dos veces — ese es el costo dominante
                         del pipeline). Si None, se fitea aquí como siempre.

    Devuelve
    --------
    DataFrame con columnas:
      fecha_t | ventana | tau | percentil_acum | y_realizado_acum
    """
    if ventanas is None:
        ventanas = [1, 5, 22, 75]
    if taus_input is None:
        taus_input = TAUS_STD
    if taus_output is None:
        taus_output = [0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]

    df_preds = df_preds.copy()
    df_preds[fecha_col] = pd.to_datetime(df_preds[fecha_col])

    # ── Fit global: una SplitT por cada (fecha_t, h) — o reusar si ya viene ──
    if distribuciones is None:
        logger.info("  [step006] Fiteando distribuciones split-t por horizonte...")
        distribuciones = fitear_distribuciones_por_horizonte(
            df_preds, taus_input, n_jobs=n_jobs)
    else:
        logger.info("  [step006] Reusando distribuciones split-t ya fiteadas...")

    # ── Calcula acumulado realizado por ventana, por fecha_t ─────────────────
    real_acum: dict[str, dict[int, float]] = {}
    for fecha_t, grp in df_preds.groupby(fecha_col):
        grp_s = grp.sort_values(h_col)
        hs    = grp_s[h_col].values
        ys    = grp_s["y_realizado"].values
        real_acum[str(fecha_t)] = {}
        for v in ventanas:
            idx = np.where(hs <= v)[0]
            real_acum[str(fecha_t)][v] = float(ys[idx].sum()) if len(idx) else np.nan

    # ── Simula paths por origen ───────────────────────────────────────────────
    fechas_origen = sorted(df_preds[fecha_col].unique())
    n_or = len(fechas_origen)
    logger.info(f"  [step006] Simulando {n_paths} paths × {n_or} orígenes × "
                f"{len(ventanas)} ventanas...")

    resultados = []
    for idx_o, fecha_t in enumerate(fechas_origen):
        df_orig = df_preds[df_preds[fecha_col] == fecha_t]
        estado_o = _resolver_estado_inicial(estado_inicial, fecha_t)
        dist_acum = simular_paths_por_origen(
            fecha_t, df_orig, distribuciones,
            estado_o, matriz_transicion, rho_por_regimen,
            n_paths=n_paths, ventanas=ventanas,
            prophet_col=prophet_col, seed=seed + idx_o,
        )
        pctiles = calcular_percentiles_acumulado(dist_acum, taus_output)

        for v, tmap in pctiles.items():
            y_real = real_acum.get(str(fecha_t), {}).get(v, np.nan)
            for tau, val in tmap.items():
                resultados.append({
                    "fecha_t":           fecha_t,
                    "ventana":           v,
                    "tau":               tau,
                    "percentil_acum":    val,
                    "y_realizado_acum":  y_real,
                })

        if (idx_o + 1) % 50 == 0:
            logger.info(f"    [step006] Origen {idx_o+1}/{n_or}")

    df_out = pd.DataFrame(resultados)
    logger.info(f"  [step006] Pipeline completo: {len(df_out):,} filas")
    return df_out


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 7 — Backtest: las tres piezas
# ══════════════════════════════════════════════════════════════════════════════

def backtest_pieza1_violaciones(
    df_sim:    pd.DataFrame,
    tau_col:   float = 0.05,
    ventana:   int = 22,
    lag_nw:    int | None = None,
) -> dict:
    """
    Pieza 1: tasa de violación con corrección Newey-West por solapamiento.

    Selecciona los registros donde tau == tau_col y ventana == ventana.

    BUG CORREGIDO: una "violación" depende de qué cola representa tau_col.
    Para tau_col<0.5 (cola inferior, p.ej. Q05 — el caso de uso de este
    proyecto: estrés de liquidez = el flujo cae POR DEBAJO del piso), la
    violación es I_t=1(realizado < percentil_predicho) — el realizado rompió
    el piso de estrés. La versión anterior usaba ">" sin importar la cola,
    lo que daba tasa_empirica≈1-τ (cerca de 0.95, no 0.05) y comparaba eso
    contra τ sin sentido, marcando pasa=False siempre sin decir nada real
    sobre la calibración del modelo. Para tau_col>0.5 (cola superior) la
    violación correcta es la dirección opuesta, I_t=1(realizado > predicho).

    Con la dirección correcta, P(I_t=1) debe acercarse a τ bajo buena
    calibración, y ahí sí la comparación contra τ es válida.

    Calcula la tasa empírica con varianza corregida por autocovarianza hasta
    lag_nw (default = ventana).

    Devuelve
    --------
    dict con: tasa_empirica, tau_nominal, ic95_lo, ic95_hi, pasa, n,
              descripcion.
    """
    sub = df_sim[
        (df_sim["tau"] == tau_col) & (df_sim["ventana"] == ventana)
    ].sort_values("fecha_t")

    if len(sub) < 5:
        return {"error": "insuficientes observaciones"}

    if tau_col < 0.5:
        # Cola inferior (estrés de liquidez): violación = romper el piso.
        I = (sub["y_realizado_acum"] < sub["percentil_acum"]).astype(float).values
    else:
        # Cola superior: violación = superar el techo.
        I = (sub["y_realizado_acum"] > sub["percentil_acum"]).astype(float).values
    n   = len(I)
    pi  = float(I.mean())

    # Varianza Newey-West con kernel de Bartlett
    L   = lag_nw if lag_nw is not None else ventana
    L   = min(L, n // 2)
    I_c = I - pi
    nw_var = float(np.dot(I_c, I_c)) / (n ** 2)
    for k in range(1, L + 1):
        w_k = 1.0 - k / (L + 1.0)
        cov_k = float(np.dot(I_c[k:], I_c[:n - k])) / (n ** 2)
        nw_var += 2.0 * w_k * cov_k
    nw_var = max(nw_var, 1e-12)
    se  = np.sqrt(nw_var)
    lo  = pi - 1.96 * se
    hi  = pi + 1.96 * se
    pasa = (lo <= tau_col <= hi)

    return {
        "tasa_empirica": round(pi, 4),
        "tau_nominal":   tau_col,
        "ic95_lo":       round(lo, 4),
        "ic95_hi":       round(hi, 4),
        "pasa":          bool(pasa),
        "n":             n,
        "ventana_dias":  ventana,
        "lag_nw":        L,
        "descripcion":   (
            f"Ventana {ventana}d | τ={tau_col:.2f} | "
            f"tasa emp={pi:.1%} vs nominal={tau_col:.1%} | "
            f"IC95%=[{lo:.3f},{hi:.3f}] | "
            f"{'✓ PASA' if pasa else '✗ FALLA'}"
        ),
    }


def backtest_pieza2_duraciones(
    df_sim:   pd.DataFrame,
    tau_col:  float = 0.05,
    ventana:  int = 22,
) -> dict:
    """
    Pieza 2: test de duraciones de Christoffersen-Pelletier.

    Ajusta una distribución exponencial (geométrica en continuo) con
    parámetro τ (bajo H0 de independencia) y una Weibull libre (b libre).
    El LR test tiene distribución χ²(1) bajo H0.

    Bajo H0: duraciones siguen Exp(τ), es decir b=1 en la Weibull.
    Si b < 1: violaciones agrupadas (peor para decisiones de liquidez).
    Si b > 1: violaciones dispersas (modelo conservador).

    Devuelve dict con: n_violaciones, duraciones_medias, b_weibull,
    lr_stat, p_valor, pasa_independencia, descripcion.
    """
    sub = df_sim[
        (df_sim["tau"] == tau_col) & (df_sim["ventana"] == ventana)
    ].sort_values("fecha_t")

    # Mismo criterio de dirección que backtest_pieza1_violaciones: para
    # tau_col<0.5 (cola inferior, estrés de liquidez) la violación es romper
    # el piso; para tau_col>0.5, superar el techo.
    if tau_col < 0.5:
        I = (sub["y_realizado_acum"] < sub["percentil_acum"]).astype(float).values
    else:
        I = (sub["y_realizado_acum"] > sub["percentil_acum"]).astype(float).values
    n = len(I)
    if n < 10:
        return {"error": "insuficientes observaciones"}

    # Instantes de violación
    t_viol = np.where(I == 1)[0]
    if len(t_viol) < 3:
        return {"error": "insuficientes violaciones para test de duraciones"}

    # Duraciones entre violaciones (incluye censura al inicio y al final)
    durs = np.diff(t_viol).astype(float)
    if len(durs) < 2:
        return {"error": "demasiado pocas duraciones"}

    # Log-verosimilitud bajo H0: Exp con λ=τ (geometrica aprox continua)
    tau_nom = tau_col
    def loglik_exp(durs, lam):
        return float(np.sum(np.log(lam) - lam * durs))

    def loglik_weibull(durs, a, b):
        if a <= 0 or b <= 0:
            return -np.inf
        return float(np.sum(np.log(b) + np.log(a) + (b-1)*np.log(durs) - a*durs**b))

    # Ajuste libre de Weibull
    try:
        def neg_ll(params):
            a, b = params
            if a <= 0 or b <= 0:
                return 1e12
            return -loglik_weibull(durs, a, b)

        res = optimize.minimize(
            neg_ll, [tau_nom, 1.0], method="L-BFGS-B",
            bounds=[(1e-6, 10.0), (1e-3, 10.0)],
            options={"maxiter": 500},
        )
        a_hat, b_hat = res.x
        ll_libre = -res.fun
    except Exception as _e_wb:
        logger.debug(f"backtest_pieza2: fallo ajuste Weibull → "
                     f"{type(_e_wb).__name__}: {_e_wb}")
        return {"error": "fallo ajuste Weibull"}

    # Log-verosimilitud restringida H0: b=1, a=τ (exponencial)
    ll_h0 = loglik_exp(durs, tau_nom)

    lr_stat = 2.0 * (ll_libre - ll_h0)
    lr_stat = max(lr_stat, 0.0)
    p_valor = float(1.0 - stats.chi2.cdf(lr_stat, df=1))

    pasa = p_valor > 0.05

    return {
        "n_violaciones":       int(len(t_viol)),
        "duracion_media":      round(float(durs.mean()), 2),
        "b_weibull":           round(float(b_hat), 4),
        "lr_stat":             round(lr_stat, 4),
        "p_valor":             round(p_valor, 4),
        "pasa_independencia":  bool(pasa),
        "interpretacion_b":    (
            "agrupadas (riesgo)" if b_hat < 0.9
            else "dispersas (conservador)" if b_hat > 1.1
            else "aproximadamente independientes"
        ),
        "descripcion": (
            f"Ventana {ventana}d | τ={tau_col:.2f} | "
            f"b_Weibull={b_hat:.3f} | LR={lr_stat:.3f} | p={p_valor:.4f} | "
            f"{'✓ PASA independencia' if pasa else '✗ FALLA independencia'}"
        ),
    }


def backtest_pieza3_pit(
    df_sim:         pd.DataFrame,
    ventana:        int = 22,
    taus_disponibles: list[float] | None = None,
    submuestrear:   bool = True,
) -> dict:
    """
    Pieza 3: PIT (Probability Integral Transform) con test Anderson-Darling.

    Para cada origen t, aproxima F̂_t(y_realizado) interpolando entre los
    cuantiles simulados disponibles. Los PITs deben ser U[0,1] si el modelo
    está calibrado.

    Parámetros
    ----------
    submuestrear : si True, usa orígenes separados por la ventana para
                   el test formal (observaciones no solapadas).

    Devuelve dict con: pits (array), A2_stat, p_valor, pasa_uniformidad,
    descripcion (+ diagnóstico de la forma del histograma).
    """
    if taus_disponibles is None:
        taus_disponibles = [0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]

    sub = df_sim[df_sim["ventana"] == ventana].copy()
    if len(sub) < 10:
        return {"error": "insuficientes observaciones"}

    # Pivot: rows=fecha_t, cols=tau, values=percentil_acum
    pivot = sub.pivot_table(index="fecha_t", columns="tau",
                            values="percentil_acum")
    pivot = pivot.sort_index()

    # Solo filas con todos los cuantiles y y_real disponible
    y_real = (sub.drop_duplicates("fecha_t")
              .set_index("fecha_t")["y_realizado_acum"]
              .sort_index())
    pivot  = pivot.loc[pivot.index.intersection(y_real.index)]
    y_real = y_real.loc[pivot.index]
    pivot  = pivot.dropna()
    y_real = y_real.loc[pivot.index].values
    taus_avail = sorted(t for t in taus_disponibles if t in pivot.columns)

    if len(taus_avail) < 3 or len(pivot) < 5:
        return {"error": "cuantiles o filas insuficientes para PIT"}

    q_mat = pivot[taus_avail].values  # shape (n_fechas, n_taus)
    n     = len(y_real)

    # PIT por interpolación lineal entre cuantiles disponibles
    pits = np.empty(n)
    for i in range(n):
        y_i = y_real[i]
        q_i = q_mat[i]
        if np.isnan(y_i) or np.any(np.isnan(q_i)):
            pits[i] = np.nan
            continue
        if y_i <= q_i[0]:
            pits[i] = taus_avail[0]
        elif y_i >= q_i[-1]:
            pits[i] = taus_avail[-1]
        else:
            pits[i] = float(np.interp(y_i, q_i, taus_avail))

    pits_clean = pits[~np.isnan(pits)]
    if len(pits_clean) < 5:
        return {"error": "insuficientes PITs válidos"}

    # Submuestreo para test formal (evita solapamiento)
    if submuestrear and len(pits_clean) > ventana:
        pits_test = pits_clean[::max(1, ventana)]
    else:
        pits_test = pits_clean

    # Anderson-Darling test de uniformidad
    try:
        ad_stat, crit_vals, sig_levels = stats.anderson(pits_test, dist="uniform")
        # p-valor aproximado: crit_vals corresponden a [15%, 10%, 5%, 2.5%, 1%]
        sig_array = np.array([0.15, 0.10, 0.05, 0.025, 0.01])
        if ad_stat >= crit_vals[-1]:
            p_aprox = 0.005
        elif ad_stat <= crit_vals[0]:
            p_aprox = 0.20
        else:
            idx_b = np.searchsorted(crit_vals, ad_stat)
            p_aprox = float(np.interp(ad_stat, crit_vals, sig_array))
    except Exception as _e_ad:
        logger.debug(f"backtest_pieza3: fallo cálculo Anderson-Darling → "
                     f"{type(_e_ad).__name__}: {_e_ad}")
        ad_stat, p_aprox = np.nan, np.nan

    pasa = (not np.isnan(p_aprox)) and (p_aprox > 0.05)

    # Diagnóstico de la forma del histograma de PITs
    p25, p50, p75 = np.percentile(pits_clean, [25, 50, 75])
    pit_mean = float(pits_clean.mean())
    if pit_mean > 0.6:
        forma = "sesgado a 1 → realizado cae sistemáticamente en la cola superior (subest. riesgo)"
    elif pit_mean < 0.4:
        forma = "sesgado a 0 → realizado cae en la cola inferior (sobreest. riesgo)"
    elif p25 < 0.15 and p75 > 0.85:
        forma = "forma U → distribución demasiado angosta (sub-cobertura)"
    elif p25 > 0.30 and p75 < 0.70:
        forma = "forma campana → distribución demasiado ancha (sobre-cobertura)"
    else:
        forma = "aproximadamente uniforme → bien calibrado"

    return {
        "n_pits":          len(pits_clean),
        "n_pits_test":     len(pits_test),
        "pit_mean":        round(pit_mean, 4),
        "pit_p25":         round(p25, 4),
        "pit_p75":         round(p75, 4),
        "A2_stat":         round(float(ad_stat), 4) if not np.isnan(ad_stat) else None,
        "p_valor_aprox":   round(p_aprox, 4) if not np.isnan(p_aprox) else None,
        "pasa_uniformidad": bool(pasa),
        "forma_histograma": forma,
        "pits":            pits_clean,
        "descripcion": (
            f"Ventana {ventana}d | PIT mean={pit_mean:.3f} | "
            f"A²={ad_stat:.3f} | p≈{p_aprox:.4f} | "
            f"{'✓ PASA uniformidad' if pasa else '✗ FALLA uniformidad'} | "
            f"{forma}"
        ),
    }


def backtest_completo(
    df_sim:     pd.DataFrame,
    tau_col:    float = 0.05,
    ventanas:   list[int] | None = None,
    lag_nw:     int | None = None,
    taus_disp:  list[float] | None = None,
) -> pd.DataFrame:
    """
    Corre las tres piezas de backtest para cada ventana de plazo.

    Devuelve DataFrame con una fila por ventana y columnas de las 3 piezas.
    """
    if ventanas is None:
        ventanas = sorted(df_sim["ventana"].unique().tolist())
    rows = []
    for v in ventanas:
        r1 = backtest_pieza1_violaciones(df_sim, tau_col, v,
                                         lag_nw=lag_nw if lag_nw else v)
        r2 = backtest_pieza2_duraciones(df_sim, tau_col, v)
        r3 = backtest_pieza3_pit(df_sim, v, taus_disponibles=taus_disp)
        rows.append({
            "ventana":              v,
            # Pieza 1
            "tasa_empirica":        r1.get("tasa_empirica"),
            "ic95_lo":              r1.get("ic95_lo"),
            "ic95_hi":              r1.get("ic95_hi"),
            "p1_pasa":              r1.get("pasa"),
            # Pieza 2
            "b_weibull":            r2.get("b_weibull"),
            "lr_p_valor":           r2.get("p_valor"),
            "p2_independencia":     r2.get("pasa_independencia"),
            "interp_b":             r2.get("interpretacion_b"),
            # Pieza 3
            "pit_mean":             r3.get("pit_mean"),
            "AD_p_valor":           r3.get("p_valor_aprox"),
            "p3_uniformidad":       r3.get("pasa_uniformidad"),
            "forma_pit":            r3.get("forma_histograma"),
        })
    return pd.DataFrame(rows)



# ══════════════════════════════════════════════════════════════════════════════
# PARTE 7b — Fan chart de flujo NETO diario y backtest puntual
# ══════════════════════════════════════════════════════════════════════════════
#
# Complemento del fan chart acumulado:
#   · Fan chart neto: muestra la distribución AzzaliniT de CADA horizonte h
#     como bandas de percentiles (no acumuladas). No necesita simulación —
#     los percentiles se leen directamente de las distribuciones ya fiteadas.
#     Las bandas no son necesariamente monótonas en h (la incertidumbre
#     pointwise no crece con el horizonte de la misma forma que la acumulada).
#   · Backtest neto: 3 piezas para τ ∈ TAUS_BACKTEST (por defecto [0.01, 0.05])
#     aplicadas directamente a las filas (fecha_t, h, y_realizado vs q_tau),
#     sin simulación. Mide calibración pointwise del XGBoost+AzzaliniT,
#     distinto del backtest acumulado que mide la cobertura del colchón.


def graficar_fanchart_neto_origen(
    fecha_t:           pd.Timestamp,
    horizontes:        np.ndarray,
    distribuciones:    dict[tuple, "AzzaliniT"],
    y_realizado_por_h: dict[int, float],
    dir_salida:        Path,
    banco:             str = "SISTEMA",
    bandas:            list[tuple[float, float]] | None = None,
    color_base:        str = "#1565C0",
) -> Path:
    """
    Fan chart de flujo neto DIARIO para UN origen, extrayendo los percentiles
    directamente de las distribuciones AzzaliniT ajustadas (sin simulación).

    A diferencia del fan chart acumulado:
      · No parte de (h=0, valor=0): cada horizonte tiene su propia distribución
        independiente centrada en su mediana predicha.
      · Las bandas pueden no ser monótonas — es información real sobre cómo
        varía la incertidumbre pointwise con el horizonte.
      · La línea realizada muestra y_realizado para cada h directamente.
    """
    if bandas is None:
        bandas = BANDAS_FANCHART_DEFAULT

    x = horizontes.tolist()
    fig, ax = plt.subplots(figsize=(10, 5.6))

    # Extraer percentiles de cada distribución analíticamente
    bandas_ord = sorted(bandas, key=lambda b: (b[1] - b[0]), reverse=True)
    n_bandas   = len(bandas_ord)

    for i, (lo_t, hi_t) in enumerate(bandas_ord):
        alpha = 0.10 + 0.55 * (i + 1) / n_bandas
        lo_vals, hi_vals = [], []
        for h in horizontes:
            dist = distribuciones.get((pd.Timestamp(fecha_t), int(h)))
            if dist is not None:
                lo_vals.append(float(dist.ppf(np.array([lo_t]))[0]))
                hi_vals.append(float(dist.ppf(np.array([hi_t]))[0]))
            else:
                lo_vals.append(np.nan)
                hi_vals.append(np.nan)
        ax.fill_between(x, lo_vals, hi_vals, color=color_base,
                        alpha=alpha, linewidth=0, zorder=2)

    med_vals = []
    for h in horizontes:
        dist = distribuciones.get((pd.Timestamp(fecha_t), int(h)))
        med_vals.append(float(dist.ppf(np.array([0.50]))[0]) if dist else np.nan)
    ax.plot(x, med_vals, color=color_base, lw=1.4, ls="--",
            label="Mediana proyectada", zorder=3)

    y_real = [y_realizado_por_h.get(int(h), np.nan) for h in horizontes]
    ax.plot(x, y_real, color="black", lw=1.9, label="Realizado", zorder=4)

    ax.axhline(0, color="grey", lw=0.6, ls=":", zorder=1)
    ax.set_xlabel("Horizonte (días hábiles desde el origen)")
    ax.set_ylabel("Flujo neto diario")
    ax.set_title(f"{banco} — Fan chart de flujo neto\nOrigen: {fecha_t.date()}",
                 fontsize=11, fontweight="bold")
    ax.legend(loc="upper left", fontsize=8, framealpha=0.9)
    ax.set_xlim(min(x), max(x))
    plt.tight_layout()

    dir_salida = Path(dir_salida)
    dir_salida.mkdir(parents=True, exist_ok=True)
    ruta = dir_salida / f"fanchart_neto_{banco}_{fecha_t.strftime('%Y%m%d')}.png"
    fig.savefig(ruta, dpi=120)
    plt.close(fig)
    return ruta


def generar_fancharts_neto_todos_origenes(
    df_preds:       pd.DataFrame,
    distribuciones: dict[tuple, "AzzaliniT"],
    dir_salida:     Path,
    banco:          str = "SISTEMA",
    h_col:          str = "h",
    fecha_col:      str = "fecha_t",
    bandas:         list[tuple[float, float]] | None = None,
) -> list[Path]:
    """
    Genera un fan chart de flujo neto PNG por cada fecha de origen en df_preds.
    No requiere simulación ni rho — solo las distribuciones ya fiteadas.
    """
    df = df_preds.copy()
    df[fecha_col] = pd.to_datetime(df[fecha_col])
    fechas = sorted(df[fecha_col].unique())
    n = len(fechas)
    logger.info(f"  [fanchart_neto] Generando {n} fan charts en {dir_salida}...")

    rutas = []
    for idx, fecha_t in enumerate(fechas):
        fecha_t = pd.Timestamp(fecha_t)
        df_o    = df[df[fecha_col] == fecha_t].sort_values(h_col)
        horizontes = df_o[h_col].values.astype(int)
        y_real_por_h = dict(zip(horizontes.tolist(),
                                df_o["y_realizado"].values.tolist()))
        try:
            ruta = graficar_fanchart_neto_origen(
                fecha_t, horizontes, distribuciones, y_real_por_h,
                dir_salida, banco=banco, bandas=bandas,
            )
            rutas.append(ruta)
        except Exception as _e:
            logger.debug(f"  [fanchart_neto] {fecha_t.date()}: {_e}")

        if (idx + 1) % 25 == 0:
            logger.info(f"    [fanchart_neto] {idx+1}/{n}")

    logger.info(f"  [fanchart_neto] {len(rutas)} imágenes generadas")
    return rutas


def backtest_flujo_neto_completo(
    df_preds:     pd.DataFrame,
    distribuciones: dict[tuple, "AzzaliniT"],
    taus_eval:    list[float] | None = None,
    horizontes_eval: list[int] | None = None,
    taus_input:   list[float] | None = None,
    h_col:        str = "h",
    fecha_col:    str = "fecha_t",
) -> pd.DataFrame:
    """
    Backtest de 3 piezas para flujos netos DIARIOS (no acumulados).

    Para cada (tau_eval, h):
      Pieza 1: tasa de violación I_t=1(y_real < q_tau) con Newey-West
      Pieza 2: test de duraciones Christoffersen-Pelletier
      Pieza 3: PIT = AzzaliniT_cdf(y_real) — Anderson-Darling

    El rol de 'ventana' lo juega 'h': cada horizonte es evaluado por separado.
    Mide calibración pointwise del XGBoost+AzzaliniT, no cobertura del colchón.

    INTERPRETACIÓN:
      · Una tasa de violación correcta a tau=0.05 significa que el Q05 del
        modelo captura el 5% de los peores flujos diarios a ESE horizonte.
      · Esto es condición necesaria pero no suficiente para que el colchón
        sea adecuado (el backtest acumulado mide lo segundo).
    """
    if taus_eval is None:
        taus_eval = [0.01, 0.05]
    if taus_input is None:
        taus_input = TAUS_STD
    if horizontes_eval is None:
        horizontes_eval = sorted(df_preds[h_col].unique().tolist())

    df = df_preds.copy()
    df[fecha_col] = pd.to_datetime(df[fecha_col])

    rows = []
    for tau in taus_eval:
        for h in horizontes_eval:
            df_h = (df[df[h_col] == h]
                    .sort_values(fecha_col)
                    .drop_duplicates(fecha_col)
                    .copy())

            if len(df_h) < 10:
                continue

            # ── Construir df_sim compatible con las piezas existentes ─────────
            # Reutiliza backtest_pieza1/2/3 con columnas renombradas
            q_col = f"q{int(tau * 100):02d}"
            if q_col not in df_h.columns:
                logger.warning(f"  [backtest_neto] columna {q_col} no encontrada")
                continue

            # PIT analítico desde AzzaliniT
            pits = []
            for _, row in df_h.iterrows():
                dist = distribuciones.get(
                    (pd.Timestamp(row[fecha_col]), int(row[h_col])))
                if dist is None:
                    pits.append(np.nan)
                    continue
                try:
                    pits.append(float(dist.cdf(np.array([float(row["y_realizado"])]))[0]))
                except Exception:
                    pits.append(np.nan)

            df_sim_h = pd.DataFrame({
                "fecha_t":          df_h[fecha_col].values,
                "ventana":          h,
                "tau":              tau,
                "percentil_acum":   df_h[q_col].values,    # q_tau de XGBoost
                "y_realizado_acum": df_h["y_realizado"].values,
            })

            # Pieza 3 necesita los PITs — los inyectamos en el formato esperado
            # construyendo un mini df_sim con todos los taus disponibles para PIT
            taus_q_disponibles = [t for t in taus_input
                                   if f"q{int(t*100):02d}" in df_h.columns]
            filas_multi = []
            for t_q in taus_q_disponibles:
                filas_multi.append(pd.DataFrame({
                    "fecha_t":          df_h[fecha_col].values,
                    "ventana":          h,
                    "tau":              t_q,
                    "percentil_acum":   df_h[f"q{int(t_q*100):02d}"].values,
                    "y_realizado_acum": df_h["y_realizado"].values,
                }))
            df_sim_multi = pd.concat(filas_multi, ignore_index=True) if filas_multi else df_sim_h

            r1 = backtest_pieza1_violaciones(df_sim_h, tau, h, lag_nw=h)
            r2 = backtest_pieza2_duraciones(df_sim_h, tau, h)
            r3 = backtest_pieza3_pit(df_sim_multi, h,
                                     taus_disponibles=taus_q_disponibles)

            # Estadísticos del PIT analítico
            pits_arr = np.array([p for p in pits if not np.isnan(p)])
            pit_mean_analitico = float(np.mean(pits_arr)) if len(pits_arr) > 0 else np.nan

            rows.append({
                "h":                h,
                "tau":              tau,
                # Pieza 1
                "tasa_empirica":    r1.get("tasa_empirica"),
                "ic95_lo":          r1.get("ic95_lo"),
                "ic95_hi":          r1.get("ic95_hi"),
                "p1_pasa":          r1.get("pasa"),
                # Pieza 2
                "b_weibull":        r2.get("b_weibull"),
                "lr_p_valor":       r2.get("p_valor"),
                "p2_independencia": r2.get("pasa_independencia"),
                "interp_b":         r2.get("interpretacion_b"),
                # Pieza 3
                "pit_mean":         pit_mean_analitico,
                "AD_p_valor":       r3.get("p_valor_aprox"),
                "p3_uniformidad":   r3.get("pasa_uniformidad"),
                "forma_pit":        r3.get("forma_histograma"),
            })

    df_out = pd.DataFrame(rows)
    if not df_out.empty:
        _print_backtest(df_out, label="BACKTEST FLUJO NETO")
    return df_out


def _print_backtest(df: pd.DataFrame, label: str = "BACKTEST") -> None:
    """Imprime el backtest en formato tabular legible con tau en la cabecera."""
    sep = "=" * 90
    print(f"\n{sep}")
    taus = df["tau"].unique() if "tau" in df.columns else [None]
    dim_col = "h" if "h" in df.columns else "ventana"
    for tau in sorted(taus):
        sub = df[df["tau"] == tau] if "tau" in df.columns else df
        tau_str = f"τ={tau:.2f}" if tau is not None else ""
        print(f"  {label}  ({tau_str})")
        print(f"{'  ' + dim_col:>10}  {'tasa_emp':>10}  {'ic95_lo':>8}  {'ic95_hi':>8}  "
              f"{'p1_pasa':>8}  {'b_weibull':>10}  {'pit_mean':>9}  {'p3_unif':>8}")
        print("-" * 90)
        for _, row in sub.iterrows():
            dim_val   = row.get(dim_col, "")
            t_emp     = f"{row.get('tasa_empirica', np.nan):.4f}" if not pd.isna(row.get('tasa_empirica', np.nan)) else "  NaN"
            ic_lo     = f"{row.get('ic95_lo', np.nan):.4f}" if not pd.isna(row.get('ic95_lo', np.nan)) else "  NaN"
            ic_hi     = f"{row.get('ic95_hi', np.nan):.4f}" if not pd.isna(row.get('ic95_hi', np.nan)) else "  NaN"
            p1        = str(row.get('p1_pasa', ""))
            bw        = f"{row.get('b_weibull', np.nan):.4f}" if not pd.isna(row.get('b_weibull', np.nan)) else "  NaN"
            pm        = f"{row.get('pit_mean', np.nan):.4f}" if not pd.isna(row.get('pit_mean', np.nan)) else "  NaN"
            p3        = str(row.get('p3_uniformidad', ""))
            print(f"  {dim_val:>8}  {t_emp:>10}  {ic_lo:>8}  {ic_hi:>8}  "
                  f"{p1:>8}  {bw:>10}  {pm:>9}  {p3:>8}")
        print()
    print(sep)


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 8 — Integración con datos reales (step005 → step006)
# ══════════════════════════════════════════════════════════════════════════════
#
# Estas funciones cierran el pendiente "estimar ρ_s por régimen" y dan el
# loader de los parquets reales que guarda step005_walk_forward_cv_4.py
# (preds_test_fold*.parquet, ya con columnas regimen_hmm/regimen_sigma/
# año_corte_regimen) y step005_validar_hmm_*.py (transmat_hmm_<banco>.parquet).
# El glue code de carpetas/rutas va en el script orquestador (step006_orquestador.py),
# no aquí — este módulo permanece agnóstico de dónde viven los archivos.

def _worker_z_fila(args: tuple) -> float:
    """
    Worker de multiprocessing para _construir_serie_z. Función de MÓDULO
    (no closure) por la misma razón que _worker_fitear_uno: picklable en
    Windows (spawn).
    """
    y, q_vals, taus = args
    dist = fitear_skewt(list(q_vals), list(taus))
    u = float(dist.cdf(np.array([y]))[0])
    return float(stats.norm.ppf(np.clip(u, 1e-6, 1 - 1e-6)))


def _pit_un_punto(y: float, q_vals: np.ndarray, taus: np.ndarray) -> float:
    """
    PIT vía la SplitT (skew-t completa) ajustada a los cuantiles predichos —
    asimetría y colas con grados de libertad finitos, deliberadamente más
    flexible que una aproximación cerrada. Costosa por fila (~0.2s,
    optimización no lineal); por eso _construir_serie_z la paraleliza con
    multiprocessing en vez de llamar esta función en un loop serial.

    Por qué no interpolación lineal con clip (el método original más viejo):
    un dato fuera de [Q01,Q99] se clavaba en PIT=0.01/0.99 sin importar cuán
    extremo fuera — pierde toda la información de magnitud en la cola, que es
    donde más importa para el régimen severo. La skew-t extrapola de forma
    continua y con la asimetría/curtosis que el ajuste encuentre.
    """
    dist = fitear_skewt(list(q_vals), list(taus))
    return float(dist.cdf(np.array([y]))[0])


def _construir_serie_z(
    df_sub:  pd.DataFrame,
    col_q:   list[str],
    taus_arr: np.ndarray,
    n_jobs:  int = -1,
) -> np.ndarray:
    """
    Calcula z_t = Φ⁻¹(PIT_t) para cada fila de df_sub, fiteando una skew-t
    completa por fila (vía _pit_un_punto / fitear_skewt) y paralelizando con
    multiprocessing — cada fit es ~0.2s (optimización no lineal); sobre series
    de miles de días el cómputo serial es impracticable (minutos).

    n_jobs : -1 usa todos los cores disponibles (os.cpu_count()); 1 fuerza
             ejecución serial. Con <50 filas siempre corre serial (el
             overhead de levantar procesos no se justifica).
    """
    tareas = [
        (float(row.y_realizado),
         tuple(getattr(row, c) for c in col_q),
         tuple(taus_arr.tolist()))
        for row in df_sub.itertuples(index=False)
    ]
    total = len(tareas)
    n_procesos = os.cpu_count() if n_jobs == -1 else n_jobs

    if n_jobs == 1 or total < 50:
        resultados = [_worker_z_fila(t) for t in tareas]
    else:
        logger.info(f"  [step006] Calculando {total} PIT/z (skew-t, "
                   f"n_jobs={n_procesos})...")
        try:
            with multiprocessing.Pool(processes=n_procesos) as pool:
                chunksize = max(1, total // (n_procesos * 4))
                resultados = pool.map(_worker_z_fila, tareas, chunksize=chunksize)
        except Exception as e:
            logger.warning(f"  [step006] multiprocessing falló ({e}); "
                          f"usando ejecución serial.")
            resultados = [_worker_z_fila(t) for t in tareas]

    return np.array(resultados)


def estimar_rho_por_regimen(
    df_preds:      pd.DataFrame,
    h_referencia:  int = 1,
    taus:          list[float] | None = None,
    max_gap_dias:  int = 4,
    rho_default:   float = 0.3,
    n_jobs:        int = -1,
) -> dict[int, float]:
    """
    Estima ρ_s (correlación AR(1) de la cópula) POR RÉGIMEN, a partir de los
    residuos reales — cierra el pendiente "estimar ρ_s por régimen (autocorr.
    de residuos de XGBoost condicionada al estado HMM)".

    Método
    ------
    1. Toma SOLO las filas con h == h_referencia (por defecto h=1, un paso
       adelante). Por construcción del problema, la predicción a horizonte h
       desde el origen t y la predicción a horizonte h+1 desde el origen t-1
       caen en el MISMO día calendario realizado — así que la serie de
       residuos a h fijo, ordenada por fecha, ES la serie temporal de
       sorpresas día a día (no hay necesidad de usar h=1..75 de un solo
       origen: es la misma información).
    2. PIT vía SplitT: u_t = F̂_t(y_realizado_t) usando la skew-t ajustada a
       los cuantiles de ESE día (ver _pit_un_punto — extrapola colas en vez
       de clavarse en Q01/Q99). z_t = Φ⁻¹(u_t) — normaliza el residuo a
       escala N(0,1), consistente con la recursión gaussiana de la cópula.
       Paralelizado con multiprocessing (ver _construir_serie_z) porque cada
       fit es ~0.2s y la serie puede tener miles de días.
    3. Para cada régimen s, calcula la autocorrelación lag-1 de z_t restringida
       a pares (t-1, t) donde: (a) el día t está clasificado en régimen s
       (mismo criterio que la simulación, que usa el régimen del paso DESTINO
       k, no el de origen), y (b) la separación calendario entre t-1 y t es
       ≤ max_gap_dias (evita correlacionar across de huecos entre folds).

    Parámetros
    ----------
    df_preds      : df_preds con columna 'regimen_hmm' ya mergeada (la que
                    guarda step005_walk_forward_cv_4.py).
    h_referencia  : horizonte (lead time) del pronóstico usado para construir
                    la serie diaria de sorpresas — NO es el rezago de la
                    autocorrelación (ese está fijo en 1 fila más abajo, ver
                    z_prev/z_cur). h_referencia responde "¿con cuánta
                    anticipación se hizo el pronóstico que comparo contra lo
                    realizado?"; el rezago responde "¿comparo cada día contra
                    el inmediatamente anterior, o contra uno más lejano?".
                    Son decisiones independientes que aquí coinciden en valor
                    por una razón distinta a "elegir el rezago": h=1 no
                    existe en datos donde T+1 ya se conoce con certeza (no es
                    una predicción), así que el horizonte mínimo con
                    incertidumbre genuina (p.ej. h=2 con convención T+2) es,
                    a la vez, el pronóstico más fresco disponible — la mejor
                    aproximación al primer paso real que se va a simular en
                    pipeline_simulacion, no un sustituto de segunda opción.
                    Cambiar h_referencia (2 vs 3, etc.) SÍ puede cambiar el
                    ρ_s estimado, porque mide la sorpresa contra pronósticos
                    con distinta anticipación — no es indiferente a esa
                    elección, aunque el rezago entre observaciones siga
                    siendo 1 día hábil en cualquier caso (def. 1).
    max_gap_dias  : separación calendario máxima entre días consecutivos
                    para que el par cuente en la autocorrelación.
    rho_default   : valor a devolver para un régimen sin suficientes
                    observaciones para estimar (con aviso).
    n_jobs        : procesos paralelos para el cálculo de PIT/z (ver
                    _construir_serie_z). -1 = todos los cores; 1 = serial.

    Devuelve
    --------
    dict {estado: ρ_s} para todos los estados presentes en 'regimen_hmm'.
    """
    if taus is None:
        taus = TAUS_STD
    if "regimen_hmm" not in df_preds.columns:
        raise ValueError("df_preds no tiene columna 'regimen_hmm' — "
                        "¿corriste step005_walk_forward_cv_4.py con "
                        "USAR_FEATURE_REGIMEN=True?")

    col_q = [f"q{int(t*100):02d}" for t in taus]
    sub = df_preds[df_preds["h"] == h_referencia].copy()
    if sub.empty:
        h_disponibles = sorted(df_preds["h"].unique().tolist())
        raise ValueError(
            f"h_referencia={h_referencia} no existe en df_preds — horizontes "
            f"disponibles: {h_disponibles[:10]}{'...' if len(h_disponibles) > 10 else ''}. "
            f"Ajusta h_referencia al horizonte mínimo real (p.ej. si tu grid "
            f"arranca en h=2 por convención T+2, usa h_referencia=2).")
    sub["fecha_t"] = pd.to_datetime(sub["fecha_t"])
    sub = sub.dropna(subset=["y_realizado", "regimen_hmm"] + col_q)
    sub = sub.sort_values("fecha_t").reset_index(drop=True)

    if len(sub) < 30:
        logger.warning(f"  [step006] solo {len(sub)} filas con h={h_referencia} "
                       f"para estimar ρ_s — resultado poco confiable.")

    taus_arr = np.array(taus)
    z = _construir_serie_z(sub, col_q, taus_arr, n_jobs=n_jobs)

    fechas   = sub["fecha_t"].values
    regimen  = sub["regimen_hmm"].values.astype(int)
    gap_dias = np.diff(fechas).astype("timedelta64[D]").astype(int)

    z_prev, z_cur, regimen_cur = z[:-1], z[1:], regimen[1:]
    valido = gap_dias <= max_gap_dias

    rho_por_regimen: dict[int, float] = {}
    for s in sorted(set(regimen.tolist())):
        mask = valido & (regimen_cur == s)
        n_validos = int(mask.sum())
        if n_validos < 30:
            logger.warning(f"  [step006] régimen {s}: solo {n_validos} pares "
                           f"válidos para autocorr. — usando ρ_default="
                           f"{rho_default}")
            rho_por_regimen[s] = rho_default
            continue
        rho = float(np.corrcoef(z_prev[mask], z_cur[mask])[0, 1])
        rho = float(np.clip(rho, -0.95, 0.95))   # evita |ρ|≈1 (degenera la recursión)
        rho_por_regimen[s] = rho
        logger.info(f"  [step006] ρ_s régimen {s}: {rho:.3f}  (n={n_validos})")

    return rho_por_regimen


def cargar_preds_test_reales(
    dir_modo: "Path",
    banco:    str,
    patron:   str = "preds_test_fold*_{banco}_*.parquet",
) -> pd.DataFrame:
    """
    Lee y concatena TODOS los preds_test_fold*.parquet de un banco, guardados
    por step005_walk_forward_cv_4.py en dir_modo (= DIR_MODO de ese script).

    Si existen varios archivos para el MISMO fold (p.ej. el pipeline se corrió
    en días distintos), se queda con el más reciente por fold (fecha_hoy más
    alta en el nombre de archivo), no con todos — evita filas duplicadas.

    Devuelve
    --------
    DataFrame único, ordenado por fecha_t y h, listo para pipeline_simulacion
    y estimar_rho_por_regimen.
    """
    from pathlib import Path as _Path
    import re

    dir_modo = _Path(dir_modo)
    archivos = sorted(dir_modo.glob(patron.format(banco=banco)))
    if not archivos:
        raise FileNotFoundError(f"No se encontraron preds_test_fold*_{banco}_*.parquet "
                                f"en {dir_modo}")

    patron_nombre = re.compile(
        rf"preds_test_fold(\d+)_{re.escape(banco)}_(\d+)\.parquet")
    mejor_por_fold: dict[int, tuple[int, "Path"]] = {}
    for ruta in archivos:
        m = patron_nombre.match(ruta.name)
        if not m:
            continue
        fold_num, fecha_hoy = int(m.group(1)), int(m.group(2))
        if fold_num not in mejor_por_fold or fecha_hoy > mejor_por_fold[fold_num][0]:
            mejor_por_fold[fold_num] = (fecha_hoy, ruta)

    rutas_finales = [r for _, r in mejor_por_fold.values()]
    logger.info(f"  [step006] {len(rutas_finales)} folds encontrados para {banco} "
               f"(de {len(archivos)} archivos en disco)")

    dfs = []
    for fold_num, (_, ruta) in sorted(mejor_por_fold.items()):
        df_f = pd.read_parquet(ruta)
        df_f["fold"] = fold_num
        dfs.append(df_f)

    df_preds = pd.concat(dfs, ignore_index=True)
    df_preds["fecha_t"] = pd.to_datetime(df_preds["fecha_t"])
    df_preds = df_preds.sort_values(["fecha_t", "h"]).reset_index(drop=True)

    dup = df_preds.duplicated(subset=["fecha_t", "h"]).sum()
    if dup > 0:
        logger.warning(f"  [step006] {dup} filas duplicadas (fecha_t,h) entre "
                       f"folds — quedándose con la primera ocurrencia.")
        df_preds = df_preds.drop_duplicates(subset=["fecha_t", "h"], keep="first")

    return df_preds


# ══════════════════════════════════════════════════════════════════════════════
# PARTE 9 — Fan charts de flujo acumulado por día de origen
# ══════════════════════════════════════════════════════════════════════════════
#
# A diferencia del backtest (que solo necesita el acumulado en 4 ventanas
# discretas: [1,5,22,75]), el fan chart necesita el acumulado en CADA
# horizonte h, para dibujar una banda que se ensancha de forma continua.
# simular_fanchart_origen calcula esto de forma eficiente: una sola pasada de
# cumsum por path (O(H)), en vez de recomputar la suma para cada ventana por
# separado (O(H²) si se reusara simular_paths_por_origen con un ventanas denso).

def simular_fanchart_origen(
    fecha_t:           pd.Timestamp,
    horizontes:        np.ndarray,
    estado_inicial:    int,
    matriz_transicion: np.ndarray,
    rho_por_regimen:   dict[int, float],
    distribuciones:    dict[tuple, SplitT],
    n_paths:           int,
    prophet_vals:      np.ndarray | None = None,
    seed:              int = 42,
) -> np.ndarray:
    """
    Simula n_paths paths para UN origen y devuelve el flujo ACUMULADO en
    CADA horizonte (no solo en ventanas discretas), vía cumsum — O(H) por
    path.

    Devuelve
    --------
    array de shape (n_paths, len(horizontes)); columna k = distribución del
    acumulado desde el origen hasta horizontes[k] (ambos extremos incluidos,
    sin contar el punto de anclaje h=0=0 que se agrega al graficar).
    """
    H = len(horizontes)
    acumulados = np.empty((n_paths, H))
    for p in range(n_paths):
        rng_p = np.random.default_rng(seed + p)
        regimenes = simular_regimen_path(estado_inicial, matriz_transicion, H, rng_p)
        residuos  = simular_un_path(fecha_t, horizontes, regimenes,
                                    rho_por_regimen, distribuciones, rng_p)
        flujos = (prophet_vals if prophet_vals is not None else 0.0) + residuos
        acumulados[p, :] = np.cumsum(flujos)
    return acumulados


# Bandas de percentiles para el fan chart, de la más angosta (centro, más
# OSCURA) a la más ancha (extremos, más CLARA) — convención estándar de fan
# chart (estilo Bank of England).
BANDAS_FANCHART_DEFAULT = [
    (0.40, 0.60), (0.30, 0.70), (0.20, 0.80),
    (0.10, 0.90), (0.05, 0.95), (0.01, 0.99),
]


def graficar_fanchart_origen(
    fecha_t:                pd.Timestamp,
    horizontes:             np.ndarray,
    acumulados:             np.ndarray,
    y_realizado_acum_por_h: dict[int, float],
    dir_salida:             Path,
    banco:                  str = "SISTEMA",
    bandas:                 list[tuple[float, float]] | None = None,
    color_base:             str = "#1565C0",
) -> Path:
    """
    Dibuja y guarda un fan chart de flujo acumulado para UN origen.

    Las bandas se dibujan de la más ANCHA a la más ANGOSTA (en ese orden),
    cada una con más opacidad que la anterior. Como están anidadas (la
    angosta es un subconjunto visual de la ancha) y matplotlib compone los
    alphas por capas, el centro queda más oscuro (cubierto por todas las
    capas) y los extremos más claros (cubiertos solo por la capa más ancha)
    — el degradado pedido, sin necesitar un gradiente continuo explícito.

    Tanto las bandas proyectadas como la línea realizada arrancan en
    (h=0, valor=0): el origen mismo, donde no hay incertidumbre ni
    acumulado todavía.
    """
    if bandas is None:
        bandas = BANDAS_FANCHART_DEFAULT

    x = [0] + horizontes.tolist()
    # figsize×dpi=120 da 1200×672 px, ambos múltiplos de 16 — evita que
    # ffmpeg tenga que redimensionar al ensamblar el video (generar_video_
    # fancharts.py), que de otro modo emite un aviso (inofensivo, pero evitable).
    fig, ax = plt.subplots(figsize=(10, 5.6))

    # de más ancha a más angosta (alpha creciente => más oscura encima)
    bandas_ordenadas = sorted(bandas, key=lambda b: (b[1] - b[0]), reverse=True)
    n_bandas = len(bandas_ordenadas)
    for i, (lo_t, hi_t) in enumerate(bandas_ordenadas):
        alpha = 0.10 + 0.55 * (i + 1) / n_bandas
        lo_vals = [0.0] + [float(np.quantile(acumulados[:, k], lo_t))
                           for k in range(len(horizontes))]
        hi_vals = [0.0] + [float(np.quantile(acumulados[:, k], hi_t))
                           for k in range(len(horizontes))]
        ax.fill_between(x, lo_vals, hi_vals, color=color_base,
                        alpha=alpha, linewidth=0, zorder=2)

    med_vals = [0.0] + [float(np.quantile(acumulados[:, k], 0.50))
                        for k in range(len(horizontes))]
    ax.plot(x, med_vals, color=color_base, lw=1.4, ls="--",
           label="Mediana proyectada", zorder=3)

    y_real = [0.0] + [y_realizado_acum_por_h.get(int(h), np.nan) for h in horizontes]
    ax.plot(x, y_real, color="black", lw=1.9, label="Realizado acumulado", zorder=4)

    ax.axhline(0, color="grey", lw=0.6, ls=":", zorder=1)
    ax.set_xlabel("Horizonte (días hábiles desde el origen)")
    ax.set_ylabel("Flujo neto acumulado")
    ax.set_title(f"{banco} — Fan chart de flujo acumulado\nOrigen: {fecha_t.date()}",
                fontsize=11, fontweight="bold")
    ax.legend(loc="upper left", fontsize=8, framealpha=0.9)
    ax.set_xlim(0, max(x))
    plt.tight_layout()

    dir_salida = Path(dir_salida)
    dir_salida.mkdir(parents=True, exist_ok=True)
    nombre = f"fanchart_{banco}_{fecha_t.strftime('%Y%m%d')}.png"
    ruta = dir_salida / nombre
    # SIN bbox_inches="tight": ese recorte depende del contenido (ancho de
    # etiquetas del eje Y varía con la magnitud de cada origen) y podría dar
    # tamaños de imagen distintos entre fechas — rompería el ensamblado de
    # video más adelante (generar_video_fancharts.py necesita frames
    # uniformes). tight_layout() ya ajusta el layout antes de guardar; el
    # tamaño final queda fijo en figsize×dpi = 1200×672 px siempre.
    fig.savefig(ruta, dpi=120)
    plt.close(fig)
    return ruta


def generar_fancharts_todos_origenes(
    df_preds:          pd.DataFrame,
    distribuciones:    dict[tuple, SplitT],
    estado_inicial:    int | dict | pd.Series,
    matriz_transicion: np.ndarray,
    rho_por_regimen:   dict[int, float],
    dir_salida:        Path,
    banco:             str = "SISTEMA",
    n_paths:           int = 1000,
    prophet_col:       str | None = None,
    h_col:             str = "h",
    fecha_col:         str = "fecha_t",
    seed:              int = 42,
    bandas:            list[tuple[float, float]] | None = None,
) -> list[Path]:
    """
    Genera un fan chart PNG por cada fecha de origen en df_preds, guardado en
    dir_salida. Reusa `distribuciones` ya fiteadas (no vuelve a ajustar
    SplitT — ese es el costo dominante, ya pagado por quien llame a esta
    función junto con pipeline_simulacion).

    Devuelve la lista de rutas de los PNGs generados, en orden cronológico.
    """
    df_preds = df_preds.copy()
    df_preds[fecha_col] = pd.to_datetime(df_preds[fecha_col])

    fechas_origen = sorted(df_preds[fecha_col].unique())
    n_or = len(fechas_origen)
    logger.info(f"  [fanchart] Generando {n_or} fan charts en {dir_salida}...")

    rutas = []
    for idx_o, fecha_t in enumerate(fechas_origen):
        fecha_t = pd.Timestamp(fecha_t)
        df_orig = df_preds[df_preds[fecha_col] == fecha_t].sort_values(h_col)
        horizontes = df_orig[h_col].values.astype(int)
        y_real     = df_orig["y_realizado"].values.astype(float)
        prophet_vals = (df_orig[prophet_col].values
                       if (prophet_col is not None and prophet_col in df_orig.columns)
                       else None)

        estado_o = _resolver_estado_inicial(estado_inicial, fecha_t)
        acumulados = simular_fanchart_origen(
            fecha_t, horizontes, estado_o, matriz_transicion, rho_por_regimen,
            distribuciones, n_paths, prophet_vals=prophet_vals, seed=seed + idx_o,
        )

        y_realizado_acum_por_h = dict(zip(horizontes.tolist(),
                                          np.cumsum(y_real).tolist()))

        ruta = graficar_fanchart_origen(
            fecha_t, horizontes, acumulados, y_realizado_acum_por_h,
            dir_salida, banco=banco, bandas=bandas,
        )
        rutas.append(ruta)

        if (idx_o + 1) % 25 == 0:
            logger.info(f"    [fanchart] {idx_o+1}/{n_or}")

    logger.info(f"  [fanchart] {len(rutas)} imágenes generadas")
    return rutas


# ══════════════════════════════════════════════════════════════════════════════
# TEST AUTOCONTENIDO
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    np.random.seed(0)
    n_fechas   = 120
    H_MAX      = 75
    TAUS       = [0.01, 0.05, 0.50, 0.95, 0.99]
    n_paths    = 300
    ventanas   = [1, 5, 22, 75]

    # ── Generar datos sintéticos que imitan output de step005 ─────────────────
    fechas   = pd.bdate_range("2022-01-03", periods=n_fechas)
    rows     = []
    rng_sim  = np.random.default_rng(1)

    for ft in fechas:
        for h in range(1, H_MAX + 1):
            mu    = 1e5 * np.sin(h / 20) + 5e4 * (1 if ft.month >= 6 else -1)
            sigma = 3e4 + 1e4 * h / H_MAX
            y     = float(rng_sim.normal(mu, sigma))
            q     = {tau: float(mu + stats.norm.ppf(tau) * sigma) for tau in TAUS}
            rows.append({
                "fecha_t":    ft,
                "h":          h,
                "y_realizado": y,
                **{f"q{int(tau*100):02d}": q[tau] for tau in TAUS},
                "prophet_pred": 0.8 * mu,  # componente determinista simulada
            })

    df_preds = pd.DataFrame(rows)
    print(f"df_preds: {df_preds.shape}  — {n_fechas} orígenes × {H_MAX} horizontes")

    # ── Configuración HMM/régimen sintética ──────────────────────────────────
    # 3 estados: 0=calma, 1=estrés moderado, 2=estrés severo
    A = np.array([[0.90, 0.08, 0.02],
                  [0.10, 0.80, 0.10],
                  [0.05, 0.15, 0.80]])
    rho_por_regimen = {0: 0.3, 1: 0.6, 2: 0.85}
    estado_inicial  = 0

    # ── Test de fit de split-t ────────────────────────────────────────────────
    row0   = df_preds[df_preds["h"] == 10].iloc[0]
    q_vals = [row0[f"q{int(t*100):02d}"] for t in TAUS]
    dist0  = fitear_skewt(q_vals, TAUS)
    print(f"\nSplit-t fiteada (h=10): loc={dist0.loc:,.0f}  "
          f"sl={dist0.scale_l:,.0f}  sr={dist0.scale_r:,.0f}  df={dist0.df:.2f}")
    q_check = {t: dist0.ppf(t) for t in TAUS}
    print("  Cuantiles reales vs fiteados:")
    for t in TAUS:
        print(f"    Q{int(t*100):02d}: real={q_vals[TAUS.index(t)]:,.0f}  "
              f"fit={q_check[t]:,.0f}")

    # ── Pipeline completo (submuestra para rapidez en el test) ───────────────
    df_preds_sub = df_preds[df_preds["fecha_t"].isin(fechas[:20])].copy()
    print(f"\nCoriendo pipeline con {len(fechas[:20])} orígenes, {n_paths} paths...")

    df_sim = pipeline_simulacion(
        df_preds_sub,
        estado_inicial    = estado_inicial,
        matriz_transicion = A,
        rho_por_regimen   = rho_por_regimen,
        ventanas          = ventanas,
        n_paths           = n_paths,
        prophet_col       = "prophet_pred",
        seed              = 42,
    )
    print(f"df_sim: {df_sim.shape}")
    print(df_sim.head(8).to_string(index=False))

    # ── Backtest completo ─────────────────────────────────────────────────────
    print("\nBacktest completo:")
    df_bt = backtest_completo(df_sim, tau_col=0.05, ventanas=ventanas)
    print(df_bt.to_string(index=False))
    print("\n✓ Test completo")
